# Stage 1: Build the application
FROM node:20 AS builder

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    unzip nano git curl nodejs npm

# Copy application to the container
WORKDIR /tmp
RUN rm -rf /tmp/*
COPY . /tmp/
RUN rm Dockerfile Jenkinsfile1
RUN npm install
RUN npm run build
RUN npx next export

# Stage 2: Finalize the image
FROM php:7.4-apache

# Copy the built application from the previous stage and give necessary permissions
COPY --from=builder /tmp/out  /var/www/html/
RUN chmod -R 755 /var/www/html

# Set up environment variables
ENV STR_CORE_PRODUCT_KEY=<secrets>
ENV STR_PRODUCT_KEY=<secrets>
ENV STR_WEB_PRODUCT_KEY=<secrets>

# Enable Apache modules and configure PHP
RUN a2enmod rewrite && \
    docker-php-ext-install mysqli && \
    docker-php-ext-enable mysqli

RUN sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start the Apache web server
CMD ["apache2-foreground"]
