# Stage 1: Build the application
FROM node:20 AS builder

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    unzip nano git curl nodejs npm

# Copy application to the container
WORKDIR /tmp
COPY . /tmp
RUN rm Dockerfile Jenkinsfile1
RUN npm install
RUN npm run build
RUN npx next export

# Stage 2: Finalize the image
FROM php:7.4-apache

# The built application from the previous stage is being copied and all necessary permissions are given
COPY --from=builder /tmp/out  /var/www/html/
RUN chmod -R 755 /var/www/html

# Enable Apache modules and configure PHP
RUN a2enmod rewrite && \
    docker-php-ext-install mysqli && \
    docker-php-ext-enable mysqli

RUN sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf

ARG kdevops_internal1_DEV_KEY
ARG kdevops_internal2_DEV_KEY
ARG kdevops_internal3_DEV_KEY

ENV kdevops_internal1_DEV_KEY=${kdevops_internal1_DEV_KEY}
ENV kdevops_internal2_DEV_KEY=${kdevops_internal2_DEV_KEY}
ENV kdevops_internal3_DEV_KEY=${kdevops_internal3_DEV_KEY}

# Expose port 80 for HTTP traffic
EXPOSE 80 

# Start the Apache web server
CMD ["apache2-foreground"]
